TRUNCATE TRACK_TIME RESTART IDENTITY;

CREATE TABLE TRACK_TIME
(
    ID               INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    NAME             VARCHAR                           NOT NULL,
    TIME             BIGINT                          NOT NULL
);